services:
  db:
    image: mysql:8.0
    container_name: his_bodega_db
    restart: always
    environment:
      TZ: America/Guatemala
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - his-net
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3308:3306"

  backend:
    build:
      context: ./his-bodega-backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      TZ: America/Guatemala
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    networks:
      - his-net
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - his-net
    ports:
      - "8080:80"

  db_backup:
    image: fradelg/mysql-cron-backup:latest
    container_name: his_bodega_db_backup
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: America/Guatemala
      # Conexión apuntando al servicio de base de datos a través de la red interna
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASS: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      # Programación en formato CRON (Todos los días a las 04:00 AM)
      CRON_TIME: "0 4 * * *"
      # Parámetros para un dump seguro en producción
      MYSQLDUMP_OPTS: "--single-transaction --quick --lock-tables=false"
      # Retención: Borra automáticamente archivos más viejos de 2 semanas
      MAX_BACKUPS: 14
      # Formato del nombre del archivo resultante
      BACKUP_SUFFIX: _his_bodega_db
    volumes:
      # Carpeta local en el host donde se guardarán los archivos .sql.gz
      - ./backups:/backup
    networks:
      - his-net

networks:
  his-net:
    driver: bridge

volumes:
  mariadb_data:
