services:
  db:
    ports:
      - "3308:3306"

  backend:
    build:
      context: ./his-bodega-backend
      dockerfile: Dockerfile.dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./his-bodega-backend:/app
      
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev --host
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/his-bodega-backend
    environment:
      - VITE_API_URL=/api
